name: CI

# we can specifi which Github events will trigger a CI build
on: push

# Now we define a single job "build" (but could define more)
jobs:

  
  build: 

    # we can also specifi the OS to run tests on
    runs-on: ubuntu-latest

    # a job is a sequence of steps

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: set up Python 3.9
        uses: actions/setup-python@v2
        with: 
          python-version: "3.9"

      - name: Install Python dependencies
        run: |
          python3 -m pip intall --upgrade pip
          pip3 install -r requirements.txt

      - name: Test with PyTest
        run: |
          python -m pytest --cov=inflammation.models tests/test_models.py